[package]
name = "example-minimal"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish = false

[dependencies]
terrarium.workspace = true

anyhow.workspace = true
wgpu.workspace = true
winit.workspace = true
